export const SESSION_SET_CLASS_LEVEL = 'SESSION_SET_CLASS_LEVEL';
export const SESSION_CLEAR_POINT = 'SESSION_CLEAR_POINT';
export const SESSION_ADD_POINT = 'SESSION_ADD_POINT';
export const SESSION_SET_HOUSE = 'SESSION_SET_HOUSE';
export const SESSION_SET_NAME = 'SESSION_SET_NAME';